# Generated by Django 4.0.3 on 2022-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
